name: C++ Cross-Platform Build & Run

on:
  workflow_dispatch:

jobs:
  build-run-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Rebuild
        run: make rebuild
        shell: bash

      - name: Run release version
        run: make run
        shell: bash

  build-run-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install build tools
        run: |
          brew install gcc || true

      - name: Rebuild
        run: make rebuild
        shell: bash

      - name: Run release version
        run: make run
        shell: bash

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Rebuild
        run: make rebuild

      - name: Run release version
        run: make run