name: C++ Cross-Platform Build & Run

on:
  workflow_dispatch:

jobs:
  build-run-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Rebuild
        run: make rebuild
        shell: bash

      - name: Run release version
        run: make run
        shell: bash

  build-run-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install build tools
        run: brew list gcc &>/dev/null || brew install gcc

      - name: Install modern Bash
        run: |
          brew install bash
          if [ -x /opt/homebrew/bin/bash ]; then
            BASH_PATH=/opt/homebrew/bin/bash
          elif [ -x /usr/local/bin/bash ]; then
            BASH_PATH=/usr/local/bin/bash
          else
            echo "Modern Bash not found. Exiting."
            exit 1
          fi
          echo "BASH_PATH=$BASH_PATH" >> $GITHUB_ENV

      - name: Rebuild
        run: make rebuild
        shell: bash

      - name: Run release version
        run: make run
        shell: bash

  build-run-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Rebuild
        run: make rebuild
        shell: bash

      - name: Run release version
        run: make run
        shell: bash