name: C++ Cross-Platform Build

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Rebuild
        run: make rebuild VERBOSE=1
        shell: bash

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          brew list gcc &>/dev/null || brew install gcc
          brew list bash &>/dev/null || brew install bash

      - name: Update path
        run: |
          if [ -x /opt/homebrew/bin ]; then
            echo "/opt/homebrew/bin" >> $GITHUB_PATH
          elif [ -x /usr/local/bin ]; then
            echo "/usr/local/bin" >> $GITHUB_PATH
          else
            echo "Bin folder not found. Exiting."
            exit 1
          fi

      - name: Rebuild
        run: make rebuild VERBOSE=1
        shell: bash

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Rebuild
        run: make rebuild VERBOSE=1
        shell: bash