name: C++ Cross-Platform Lint

on:
  workflow_dispatch:

jobs:
  lint-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format clang-tidy

      - name: Lint
        run: make lint
        shell: bash

  lint-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install build tools
        run: brew install clang-format clang-tidy

      - name: Install modern Bash
        run: |
          brew install bash
          if [ -x /opt/homebrew/bin/bash ]; then
            BASH_PATH=/opt/homebrew/bin/bash
          elif [ -x /usr/local/bin/bash ]; then
            BASH_PATH=/usr/local/bin/bash
          else
            echo "Modern Bash not found. Exiting."
            exit 1
          fi
          echo "BASH_PATH=$BASH_PATH" >> $GITHUB_ENV

      - name: Lint
        run: make lint
        shell: bash

  lint-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Lint
        run: make lint
        shell: bash