name: C++ Cross-Platform Lint

on:
  workflow_dispatch:

jobs:
  lint-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt-get update
          if ! dpkg -s clang-tidy &>/dev/null; then  
            sudo apt-get install -y clang-tidy
          fi
          if ! dpkg -s clang-format &>/dev/null; then
            sudo apt-get install -y clang-format
          fi

      - name: Lint
        run: make -j lint 2>&1 | tee lint-linux-output.txt

      - name: Upload lint results
        uses: actions/upload-artifact@v4
        with:
          name: lint-linux-output
          path: lint-linux-output.txt

  lint-macos:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          brew list llvm &>/dev/null || brew install llvm
          brew list bash &>/dev/null || brew install bash

      - name: Update path
        run: |
          if [ -x /opt/homebrew/bin ]; then
            echo "/opt/homebrew/bin" >> $GITHUB_PATH
          elif [ -x /usr/local/bin ]; then
            echo "/usr/local/bin" >> $GITHUB_PATH
          else
            echo "Bin folder not found. Exiting."
            exit 1
          fi
          if [ -x /opt/homebrew/opt/llvm/bin ]; then
            echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH
          elif [ -x /usr/local/opt/llvm/bin ]; then
            echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH
          else
            echo "Bin folder not found. Exiting."
            exit 1
          fi

      - name: Lint
        run: make -j lint 2>&1 | tee lint-macos-output.txt

      - name: Upload lint results
        uses: actions/upload-artifact@v4
        with:
          name: lint-macos-output
          path: lint-macos-output.txt

  lint-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          if ! command -v clang-tidy &>/dev/null || ! command -v clang-format &>/dev/null; then
            powershell -Command "choco install llvm -y"
          fi

      - name: Update path
        run: echo "C:\\Program Files\\LLVM\\bin" >> $GITHUB_PATH

      - name: Lint
        run: make -j lint 2>&1 | tee lint-windows-output.txt

      - name: Upload lint results
        uses: actions/upload-artifact@v4
        with:
          name: lint-windows-output
          path: lint-windows-output.txt